### ISSUE TITLE
ArXiv RSS vs. endpoint

### ISSUE THREAD

**Issue by xiamengzhou** [tatsu-lab/gpt_paper_assistant#8]
Hi, thanks for the awesome project!

I noticed that both the ArXiv RSS feed and the endpoint are used to scrape ArXiv papers. The code mentions that the RSS feed is buggy, and sometimes drops new papers. Given this, wouldn't it be more reliable to exclusively use the endpoint instead?

**Comment by thashim** [comment]
I think Arxiv did something to their RSS that broke everything by changing the format, but also covers most if not all the papers. For now, I'm switching to RSS only and seeing if it misses any papers.
